# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  token-job:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    name: Obtain and Use JWT
    steps:
      - name: Get JWT
        id: auth-token
        run: |
          echo "TOKEN=$(curl -sSL -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL")" >> $GITHUB_ENV
          echo "JWT Token acquired."
          echo $TOKEN | jq .value | base64

      - name: Authenticate with API
        id: api-auth
        run: |
          echo "Received token: $TOKEN"
          echo $TOKEN | jq .value | base64
          export SHORT_LIVE_TOKEN=$(curl -vvvk --request POST "https://devops-service.secretsmgr.cyberark.cloud/api/authn-jwt/public-github/conjur/host%2Fdata%2Ftest-github/authenticate" \
            --header "Content-Type: application/x-www-form-urlencoded" \
            --header "Accept-Encoding: base64" \
            --data-urlencode jwt="$TOKEN")
          echo "Authentication request sent."
          echo "Received token: $SHORT_LIVE_TOKEN"
