run-name: Test CyberArk Integration
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch test
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

 
jobs:
  cyberark-integration:
    permissions:
      id-token: 'write'
      contents: 'read'
    runs-on: ubuntu-latest
 
    steps:


      - name: Import Secrets using CyberArk Conjur Secret Fetcher
        uses: cyberark/conjur-action@v2.0.6
        with:
          url: https://devops-service.secretsmgr.cyberark.cloud
          account: conjur
          authn_id: authn-jwt/public-github
          host_id: host/data/test-github
          secrets: data/vault/RobinB-SafeSecretHub/TestOutOfSync/password
      
      - name: echo secrets
        run: |
          echo ${password} | base64
          echo ${password} | sed 's/./& /g'
          echo ${PASSWORD} > test
          cat test
          echo ${PASSWORD} | sed 's/./& /g'
          echo ${TOKEN}
          echo ${TOKEN} | sed 's/./& /g'
          # | sets the result into an env variable
